apiVersion: batch/v1
kind: Job
metadata:
  name: math-add-job
spec:
  template:
    spec:  # This comes from pod definition file
      containers:
        - name: math-add
          image: ubuntu
          command: [ "expr", "3", "+" , "2" ]
      restartPolicy: Always
