apiVersion: batch/v1
kind: Job
metadata:
  name: math-add-job
spec:
  template:
    spec:  # This comes from pod definition file
      completions: 3 # Specifies the no. of pods that need to be created to run this task, pods will be created SEQUENTIALLY
      parallelism: 3 # pods will be created "PARALLELY"
      containers:
        - name: math-add
          image: ubuntu
          command: [ "expr", "3", "+" , "2" ]
      restartPolicy: Always