apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp
  labels:
    app: app1
    function: Front-end
  annotations:  # for informational purposes
    buildVersion: 1.34
spec:
  containers:
    - name: simple-webapp
      image: simple-webapp