apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: simple-webapp
  labels:
    app: App1
    function: Front-end
  annotations:  # for informational purposes
    buildVersion: 1.34
spec:
  replicas: 3
  selector:
    matchLabels:
      app: App1   # tries to discover pods with this label
  template:
    metadata:
      labels:
        app: App1
        function: Front-end
    spec:
      containers:
      - name: simple-webapp
        image: simple-webapp