apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: myapp
spec:
  containers:
    - name: nginx-container
      image: nginx
  serviceAccountName: my_service_account
  automountServiceAccount: false # if we don't want to auto mount default service account