apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
  - name: data-processor
    image: data-processor
  nodeSelector:
    size: Large  # This is a lable in the node definition as key value pair (size=Large), check "kubectl describe node node01"