apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
    - name: data-processor
      image: data-processor
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: # other types of node affinity also exists check he README file
        nodeSelectorTerms:
        - matchExpressions:
          - key: size
            operator: In # "NotIn" can also be used to for exclusion,
                         # "Exists" operator make sure the label size exists in the nodes as a precondition to place pods on nodes
            values:
            - Large   # This ensures the pod will be placed in nodes with labels either Large or Medium
            - Medium
