apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-role-binding
subjects: # A user to be assigned in a given role
  - kind: User
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io
roleRef:  # Role to be assigned
  kind: ClusterRole
  name: cluster-administrator
  apiGroup: rbac.authorization.k8s.io

