apiVersion: v1
kind: Config
current-context: my-kube-admin@my-kube-playground # Sets the current-context
clusters:
  - name: my-kube-playground
    cluster:
      certificate-authority: /etc/kubernetes/pki/ca.crt
#      certificate-authority-data: cat ca.crt | base64 # optionally we can use this
      server: https://my-kube-playground:6443

contexts:
  - name: my-kube-admin@my-kube-playground
    context:
      cluster: my-kube-playground
      user: my-kube-admin
      namespace: finance
users:
  - name: my-kube-admin
    user:
      client-certificate: /etc/kubernetes/pki/users/admin.crt
      client-key: /etc/kubernetes/pki/users/admin.key
