apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devuser-developer-binding
subjects: # A user to be assigned in a given role
  - kind: User
    name: dev-user
    apiGroup: rbac.authorization.k8s.io
roleRef:  # Role to be assigned
  kind: Role
  name: Developer
  apiGroup: rbac.authorization.k8s.io

