apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
rules:
  - apiGroups: [""] # either named or core group. for core group we can leave it as blank
    resources: ["pods"] # this is the resource upon which the actions are applied
    verbs: ["list","get", "create","update","delete"] # These are the actions
  - apiGroups: [""]
    resources: ["configMap"]
    verbs: ["create"]
    resourceNames: ["blue", "orange"] # This allows further resitricting access to specific pod names