apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        type: frontend
    spec:
      containers:
      - name: nginx-controller
        image: {{ Values.image }} # Refers to the values file
  replicas: 3

