apiVersion: v1
kind: Service
metadata:
  name: mysql-h
spec:
  type: NodePort
  ports:
    - port: 3380
  selector:
    app: mysql
  clusterIP: None # The only differentiator to make a service headless

