apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: google-storage # Refers to the storage class that has been defined.
  resources:
    requests:
      storage: 500Mi