apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql-headless # headless serviceName, will be considered as sub-domain-name for DNS record
  podManagementPolicy: Parallel # Avoid ordered approach when scaling down and scaling up.
                                # Default value is : OrderedReady