apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: myapp
spec:
  containers:
    - name: myapp
      image: myapp
      ports:
        - containerPort: 8080
    - name: log-agent
      image: log-agent